version: '3.3'
services:
  mysql:
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_DATABASE: 'homework'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql
volumes:
  my-db: